/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'tenant-settings': TenantSetting;
    players: Player;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'tenant-settings': TenantSettingsSelect<false> | TenantSettingsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'hero-settings': HeroSetting;
    'brand-settings': BrandSetting;
    'theme-settings': ThemeSetting;
    'stats-settings': StatsSetting;
    'schedule-settings': ScheduleSetting;
  };
  globalsSelect: {
    'hero-settings': HeroSettingsSelect<false> | HeroSettingsSelect<true>;
    'brand-settings': BrandSettingsSelect<false> | BrandSettingsSelect<true>;
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
    'stats-settings': StatsSettingsSelect<false> | StatsSettingsSelect<true>;
    'schedule-settings': ScheduleSettingsSelect<false> | ScheduleSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Per-tenant settings for brand, hero, theme, stats, and schedule.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-settings".
 */
export interface TenantSetting {
  id: string;
  tenantId: string;
  brand?: {
    brandName?: string | null;
    brandSubtitle?: string | null;
    /**
     * Single letter or short mark (e.g., "W" for Westfield)
     */
    brandMark?: string | null;
    /**
     * Team motto or tagline displayed in the footer
     */
    brandMoto?: string | null;
    brandLogo?: (string | null) | Media;
  };
  hero?: {
    season?: string | null;
    headline?: string | null;
    heroDescription?: string | null;
    backgroundImage?: (string | null) | Media;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    /**
     * Button background color. Accepts hex (#EBBA3C) or HSL (43 90% 55%).
     */
    primaryCtaBackgroundColor?: string | null;
    /**
     * Button text color. Accepts hex (#000000) or HSL (0 0% 0%).
     */
    primaryCtaTextColor?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    tertiaryCtaLabel?: string | null;
    tertiaryCtaHref?: string | null;
    quaternaryCtaLabel?: string | null;
    quaternaryCtaHref?: string | null;
  };
  theme?: {
    light?: {
      /**
       * Main brand color. Accepts hex (#EBBA3C) or HSL (43 90% 55%).
       */
      primary?: string | null;
      /**
       * Accent color. Accepts hex (#030712) or HSL (43 90% 55%).
       */
      secondary?: string | null;
    };
    dark?: {
      /**
       * Main brand color. Accepts hex (#EBBA3C) or HSL (43 90% 55%).
       */
      primary?: string | null;
      /**
       * Accent color. Accepts hex (#030712) or HSL (43 90% 55%).
       */
      secondary?: string | null;
    };
  };
  stats?: {
    items?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  schedule?: {
    seasonLabel?: string | null;
    title?: string | null;
    record?: string | null;
    /**
     * Background color for Win (W) outcome chips. Accepts hex or HSL.
     */
    winChipBackgroundColor?: string | null;
    /**
     * Text color for Win (W) outcome chips. Accepts hex or HSL.
     */
    winChipTextColor?: string | null;
    games?:
      | {
          dateTime: string;
          opponent: string;
          location: 'Home' | 'Away';
          status: 'final' | 'upcoming';
          result?: string | null;
          outcome?: ('W' | 'L' | 'T' | 'BYE') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: string;
  /**
   * URL slug, e.g. "marcus-johnson"
   */
  slug?: string | null;
  name: string;
  number?: string | null;
  position?: string | null;
  positionGroup?: ('Offense' | 'Defense' | 'Special Teams')[] | null;
  /**
   * Graduation year (e.g., 2026).
   */
  year?: string | null;
  height?: string | null;
  weight?: string | null;
  image?: (string | null) | Media;
  stats?: string | null;
  /**
   * Link to the player Hudl profile (e.g., https://www.hudl.com/...).
   */
  hudlUrl?: string | null;
  bio?: string | null;
  accolades?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional ordering value (lower comes first).
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'tenant-settings';
        value: string | TenantSetting;
      } | null)
    | ({
        relationTo: 'players';
        value: string | Player;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-settings_select".
 */
export interface TenantSettingsSelect<T extends boolean = true> {
  tenantId?: T;
  brand?:
    | T
    | {
        brandName?: T;
        brandSubtitle?: T;
        brandMark?: T;
        brandMoto?: T;
        brandLogo?: T;
      };
  hero?:
    | T
    | {
        season?: T;
        headline?: T;
        heroDescription?: T;
        backgroundImage?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        primaryCtaBackgroundColor?: T;
        primaryCtaTextColor?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        tertiaryCtaLabel?: T;
        tertiaryCtaHref?: T;
        quaternaryCtaLabel?: T;
        quaternaryCtaHref?: T;
      };
  theme?:
    | T
    | {
        light?:
          | T
          | {
              primary?: T;
              secondary?: T;
            };
        dark?:
          | T
          | {
              primary?: T;
              secondary?: T;
            };
      };
  stats?:
    | T
    | {
        items?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  schedule?:
    | T
    | {
        seasonLabel?: T;
        title?: T;
        record?: T;
        winChipBackgroundColor?: T;
        winChipTextColor?: T;
        games?:
          | T
          | {
              dateTime?: T;
              opponent?: T;
              location?: T;
              status?: T;
              result?: T;
              outcome?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  number?: T;
  position?: T;
  positionGroup?: T;
  year?: T;
  height?: T;
  weight?: T;
  image?: T;
  stats?: T;
  hudlUrl?: T;
  bio?: T;
  accolades?:
    | T
    | {
        title?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-settings".
 */
export interface HeroSetting {
  id: string;
  season?: string | null;
  headline?: string | null;
  heroDescription?: string | null;
  backgroundImage?: (string | null) | Media;
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  /**
   * Button background color. Accepts hex (#EBBA3C) or HSL (43 90% 55%).
   */
  primaryCtaBackgroundColor?: string | null;
  /**
   * Button text color. Accepts hex (#000000) or HSL (0 0% 0%).
   */
  primaryCtaTextColor?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  tertiaryCtaLabel?: string | null;
  tertiaryCtaHref?: string | null;
  quaternaryCtaLabel?: string | null;
  quaternaryCtaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-settings".
 */
export interface BrandSetting {
  id: string;
  brandName?: string | null;
  brandSubtitle?: string | null;
  /**
   * Single letter or short mark (e.g., "W" for Westfield)
   */
  brandMark?: string | null;
  /**
   * Team motto or tagline displayed in the footer
   */
  brandMoto?: string | null;
  brandLogo?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure theme colors for light and dark modes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: string;
  light?: {
    /**
     * Main brand color. Accepts hex (#EBBA3C) or HSL (43 90% 55%).
     */
    primary?: string | null;
    /**
     * Accent color. Accepts hex (#030712) or HSL (43 90% 55%).
     */
    secondary?: string | null;
  };
  dark?: {
    /**
     * Main brand color. Accepts hex (#EBBA3C) or HSL (43 90% 55%).
     */
    primary?: string | null;
    /**
     * Accent color. Accepts hex (#030712) or HSL (43 90% 55%).
     */
    secondary?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats-settings".
 */
export interface StatsSetting {
  id: string;
  items?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-settings".
 */
export interface ScheduleSetting {
  id: string;
  seasonLabel?: string | null;
  title?: string | null;
  record?: string | null;
  /**
   * Background color for Win (W) outcome chips. Accepts hex or HSL.
   */
  winChipBackgroundColor?: string | null;
  /**
   * Text color for Win (W) outcome chips. Accepts hex or HSL.
   */
  winChipTextColor?: string | null;
  games?:
    | {
        dateTime: string;
        opponent: string;
        location: 'Home' | 'Away';
        status: 'final' | 'upcoming';
        result?: string | null;
        outcome?: ('W' | 'L' | 'T' | 'BYE') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-settings_select".
 */
export interface HeroSettingsSelect<T extends boolean = true> {
  season?: T;
  headline?: T;
  heroDescription?: T;
  backgroundImage?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  primaryCtaBackgroundColor?: T;
  primaryCtaTextColor?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  tertiaryCtaLabel?: T;
  tertiaryCtaHref?: T;
  quaternaryCtaLabel?: T;
  quaternaryCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-settings_select".
 */
export interface BrandSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandSubtitle?: T;
  brandMark?: T;
  brandMoto?: T;
  brandLogo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  light?:
    | T
    | {
        primary?: T;
        secondary?: T;
      };
  dark?:
    | T
    | {
        primary?: T;
        secondary?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats-settings_select".
 */
export interface StatsSettingsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-settings_select".
 */
export interface ScheduleSettingsSelect<T extends boolean = true> {
  seasonLabel?: T;
  title?: T;
  record?: T;
  winChipBackgroundColor?: T;
  winChipTextColor?: T;
  games?:
    | T
    | {
        dateTime?: T;
        opponent?: T;
        location?: T;
        status?: T;
        result?: T;
        outcome?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}